#ifndef UNIXCW_CWUTILS_LIB_MISC_H
#define UNIXCW_CWUTILS_LIB_MISC_H




#include <stdio.h>

#include <libcw_gen.h>

#include "elements.h"




/**
   @brief Return ideal duration of element of given type

   "ideal" means here a duration of element if it was generated by ideal
   generator at specific speed. Implementation of libcw and other factors may
   result in actual duration of actual element to be different than the
   ideal.

   Use @p durations as source of information on what is the ideal duration of
   element of given @p type.

   @param[in] type Type of element for which to get ideal duration.
   @param[in] durations Information on durations taken from a generator

   @return Duration of element of type @p type.
*/
int ideal_duration_of_element(cw_element_type_t type, cw_gen_durations_t * durations);




/**
   @brief Print @p durations structure to given @p file

   This is just a debug function.

   @param[out] file File to which to print info on @p durations
   @param[in] durations Durations to print
*/
void cw_durations_print(FILE * file, cw_gen_durations_t * durations);




#endif /* #ifndef UNIXCW_CWUTILS_LIB_MISC_H */

